import {test,expect} from '@playwright/test';
test('real isolated worker slider computes, cancels superseded work, pans frozen plots and preserves notebook bindings',async({page})=>{
 await page.setViewportSize({width:1280,height:960});await page.goto('/');
 await page.getByRole('button',{name:'＋ Math',exact:true}).click();
 const editor=page.getByRole('textbox',{name:'Math input 1',exact:true});
 await editor.fill('let a=99;let rate=2;explore(a^2+rate,controls:{a:0..4},initial:{a:2})');await editor.press('ControlOrMeta+Enter');await editor.press('Escape');
 const explore=page.locator('.explore-view');const slider=explore.getByRole('slider',{name:'Explore parameter a'});
 await expect(slider).toBeEnabled();await expect(explore).toContainText('6');
 await slider.press('End');await expect(explore).toHaveAttribute('aria-busy','false');await expect(explore).toContainText('18');
 await slider.press('Home');for(let i=0;i<100;i++)await slider.press('ArrowRight');
 await expect(explore).toHaveAttribute('aria-busy','false');await expect(explore).toContainText('6');
 await page.screenshot({path:'test-results/explore-scalar.png',fullPage:true});
 await editor.fill('let a=99;explore(plot(a*x,x:0..1),controls:{a:0..4},initial:{a:2})');await editor.press('ControlOrMeta+Enter');await editor.press('Escape');
 await expect(slider).toBeEnabled();await slider.press('End');await expect(explore).toHaveAttribute('aria-busy','false');
 const plot=explore.locator('.plot-view'),svg=plot.getByRole('img',{name:'Plot',exact:true});
 await expect(plot).toHaveAttribute('aria-busy','false');await svg.press('ArrowRight');await expect(plot).toHaveAttribute('aria-busy','false');
 await plot.locator('summary').click();await expect(plot.locator('.plot-sample-data')).toContainText('4');
 await page.screenshot({path:'test-results/explore-plot.png',fullPage:true});
 await page.getByRole('button',{name:'＋ Math',exact:true}).click();const probe=page.getByRole('textbox',{name:'Math input 2',exact:true});await probe.fill('a');await probe.press('ControlOrMeta+Enter');await probe.press('Escape');
 await expect(page.locator('.notebook-cell').nth(1).locator('.cell-output')).toContainText('99');
 await page.setViewportSize({width:390,height:900});
 const close=page.locator('.inspector').getByRole('button',{name:'Close',exact:true});if(await close.isVisible())await close.click();
 await slider.scrollIntoViewIfNeeded();await expect(slider).toHaveValue('4');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/explore-narrow.png',fullPage:true});
 await page.setViewportSize({width:1280,height:960});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save',exact:true}).first().click();
 const file=await download;const path=await file.path();if(!path)throw new Error('no saved source');const {readFile}=await import('node:fs/promises');const saved=await readFile(path,'utf8');
 expect(saved).toContain('initial:');expect(saved).not.toContain('context');expect(saved).not.toContain('view_id');
});
