import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('real L2 source shows high precision report and proportional markers and exports Unicode SVG',async({page})=>{
 await page.setViewportSize({width:1280,height:960});await page.goto('/');await page.getByRole('button',{name:'＋ Math',exact:true}).click();
 const editor=page.getByRole('textbox',{name:'Math input 1',exact:true});
 await editor.fill(await readFile(new URL('../../docs/examples/earth-moon-l2.om',import.meta.url),'utf8'));await editor.press('ControlOrMeta+Enter');await editor.press('Escape');
 const plot=page.locator('.plot-view');await expect(plot).toBeVisible();await expect(plot.getByRole('alert')).toHaveCount(0);
 await expect(page.getByRole('rowheader',{name:'barycentric_km',exact:true})).toBeVisible();
 await expect(plot.locator('svg circle')).toHaveCount(4);await expect(plot.locator('svg text').filter({hasText:'月球'})).toBeVisible();
 const xs=await plot.locator('svg circle').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('cx'))));
 expect((xs[3]!-xs[2]!)/(xs[2]!-xs[0]!)).toBeCloseTo(64514.9072421657/384400,10);
 await plot.screenshot({path:'test-results/scenario-l2.png'});
 const download=page.waitForEvent('download');await plot.getByRole('button',{name:'Export SVG',exact:true}).click();const file=await download;const path=await file.path();if(!path)throw new Error('No actual SVG');
 const svg=await readFile(path,'utf8');expect(svg).toContain('地球');expect(svg).toContain('月球');expect(svg).toContain('444244.22260083933');
 await plot.getByRole('button',{name:'Zoom in',exact:true}).click();await expect(plot).toHaveAttribute('aria-busy','false');await expect(plot.getByRole('alert')).toHaveCount(0);
});
test('complete watermelon is actual kernel geometry with skin cut rind seeds GPU rotation and OBJ readback',async({page})=>{
 await page.setViewportSize({width:1280,height:960});await page.goto('/');await page.getByRole('button',{name:'＋ Math',exact:true}).click();
 const editor=page.getByRole('textbox',{name:'Math input 1',exact:true});
 await editor.fill(await readFile(new URL('../../docs/examples/watermelon.om',import.meta.url),'utf8'));await editor.press('ControlOrMeta+Enter');await editor.press('Escape');
 const scene=page.locator('.scene-view');await expect(scene).toBeVisible({timeout:30_000});await expect(scene.getByRole('alert')).toHaveCount(0);
 const canvas=scene.locator('canvas');await expect(canvas).toBeVisible();
 const pixels=()=>canvas.evaluate((c:HTMLCanvasElement)=>{const gl=c.getContext('webgl2')!;const a=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,a);let green=0,red=0,dark=0,sum=0;for(let i=0;i<a.length;i+=4){const r=a[i]!,g=a[i+1]!,b=a[i+2]!;if(g>r*1.7&&g>b*1.3)green++;if(r>g*1.6&&r>b*1.1)red++;if(r<65&&g<65&&b<65)dark++;sum=(sum+r*3+g*7+b*11)%1_000_000_007;}return {green,red,dark,sum};});
 const first=await pixels();expect(first.green).toBeGreaterThan(500);expect(first.red).toBeGreaterThan(200);expect(first.dark).toBeGreaterThan(20);
 await scene.screenshot({path:'test-results/scenario-watermelon.png'});
 await scene.getByRole('button',{name:'Rotate right',exact:true}).click();await expect.poll(async()=>(await pixels()).sum).not.toBe(first.sum);
 await scene.getByRole('button',{name:'Reset view',exact:true}).click();await expect.poll(async()=>(await pixels()).sum).toBe(first.sum);
 const download=page.waitForEvent('download');await scene.getByRole('button',{name:'Export OBJ',exact:true}).click();const file=await download;const path=await file.path();if(!path)throw new Error('No actual OBJ');
 const obj=await readFile(path,'utf8');const data=JSON.parse(obj.split('\n').find(v=>v.startsWith('# scene_json '))!.slice(13)).scene;
 expect(data.meshes).toHaveLength(16);expect(data.labels).toHaveLength(2);
 expect(obj.split('\n').filter(v=>v.startsWith('f ')).length).toBe(data.meshes.reduce((n:number,m:{triangles:unknown[]})=>n+m.triangles.length,0));
 await page.setViewportSize({width:390,height:900});const close=page.locator('.inspector').getByRole('button',{name:'Close',exact:true});if(await close.isVisible())await close.click();await canvas.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await scene.screenshot({path:'test-results/scenario-watermelon-narrow.png'});
});
