[package]
name = "om-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Symbolic expressions and canonical constructors"

[dependencies]
om-num.workspace = true
smallvec.workspace = true
rustc-hash.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
