/* Generated by scripts/native_contracts.py. Lifecycle implementations: R4.0.06. */
#ifndef OPENMATH_HOST_H
#define OPENMATH_HOST_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct om_host_handle om_host_handle;
typedef struct { unsigned char *ptr; size_t len; } om_host_buffer;
typedef struct { om_host_handle *handle; om_host_buffer error; } om_host_create_result;
/* Returned buffers are Rust-owned; free once (NULL/0 is empty). Version C string is static.
 * Handles are opaque registry keys: never dereference/free. close_finish is background-only.
 * cancel: 1 stop signalled, 0 terminal, -1 argument, -2 reference, -3 closing, -4 internal, -5 budget.
 * close_finish: 0 consumed, -2 invalid/consumed, -4 internal. No function unwinds across C. */
uint32_t om_host_abi_version(void);
const char * om_host_kernel_release_version(void);
uint32_t om_host_metadata_version(void);
om_host_create_result om_host_create(const unsigned char *json, size_t len);
om_host_buffer om_host_submit(om_host_handle *host, const unsigned char *json, size_t len);
om_host_buffer om_host_next_events(om_host_handle *host, uint32_t wait_ms, size_t max_bytes);
om_host_buffer om_host_read_snapshot(om_host_handle *host, const unsigned char *query_json, size_t len);
om_host_buffer om_host_source_command(om_host_handle *host, const unsigned char *json, size_t len);
int32_t om_host_cancel(om_host_handle *host, const unsigned char *operation_id, size_t len);
om_host_buffer om_host_close_begin(om_host_handle *host);
int32_t om_host_close_finish(om_host_handle *host);
void om_host_buffer_free(om_host_buffer buffer);
#ifdef __cplusplus
}
#endif
#endif
