/* Generated by scripts/native_contracts.py. Lifecycle implementations: R4.0.06. */
#ifndef OPENMATH_HOST_H
#define OPENMATH_HOST_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct om_host_handle om_host_handle;
typedef struct { unsigned char *ptr; size_t len; } om_host_buffer;
typedef struct { om_host_handle *handle; om_host_buffer error; } om_host_create_result;
/* Returned buffers are Rust-owned; free once. Version C string is immutable/static and never freed. */
uint32_t om_host_abi_version(void);
const char * om_host_kernel_release_version(void);
uint32_t om_host_metadata_version(void);
om_host_create_result om_host_create(const unsigned char *json, size_t len);
om_host_buffer om_host_submit(om_host_handle *host, const unsigned char *json, size_t len);
om_host_buffer om_host_next_events(om_host_handle *host, uint32_t wait_ms, size_t max_bytes);
int32_t om_host_cancel(om_host_handle *host, const unsigned char *operation_id, size_t len);
om_host_buffer om_host_close_begin(om_host_handle *host);
int32_t om_host_close_finish(om_host_handle *host);
void om_host_buffer_free(om_host_buffer buffer);
#ifdef __cplusplus
}
#endif
#endif
