[package]
name = "om-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "OpenMath desktop frontend"

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
om-kernel = { workspace = true, features = ["native"] }
tauri.workspace = true
om-num.workspace = true
om-llm = {workspace=true,features=["http"]}
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true

[dev-dependencies]
wiremock.workspace = true

[lints]
workspace = true
