[package]
name = "om-llm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Sans-IO configurable LLM integration"

[features]
default = []
http = []

[dependencies]
om-num.workspace = true
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
om-parse.workspace = true
om-format.workspace = true
