"""Generate Rust and Swift DTO fields from native host/editor machine contracts."""
from pathlib import Path
import argparse
import hashlib
import json
import re
import sys
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ['macos-host-state.schema.json', 'macos-editor-rendering.schema.json', 'native-host-wire.schema.json', 'native-source-store.schema.json']
PRIMITIVES = {'CellIdentity': ('String', 'String'), 'Identity': ('String', 'String'), 'Sha256': ('String', 'String'),
              'Serial': ('Serial', 'HostSerial'), 'BlobHash': ('String', 'String'), 'Timestamp': ('String', 'String'), 'ByteOffset': ('u32', 'UInt32')}
models = {}
inputs = []
for name in SOURCES:
    path = ROOT / 'docs/design' / name
    data = json.loads(path.read_text(encoding='utf-8'))
    inputs.append({'path': str(path.relative_to(ROOT)), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
    for key, value in data['$defs'].items():
        if key in models and key not in PRIMITIVES and {k:v for k,v in models[key].items() if k not in ('description','title')} != {k:v for k,v in value.items() if k not in ('description','title')}:
            sys.exit(f'Conflicting definition: {key}')
        models[key] = value

def snake(name):
    if name == name.upper():
        return name.lower()
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

def pascal(name):
    if name == name.upper():
        name = name.lower()
    return ''.join(x[:1].upper() + x[1:] for x in re.split(r'[^A-Za-z0-9]+', name))

def type_pair(schema, name):
    if 'const' in schema and isinstance(schema['const'], str):
        models.setdefault(name, {'type':'string','enum':[schema['const']]})
        return name,name
    if '$ref' in schema:
        key = schema['$ref'].rsplit('/', 1)[-1]
        return PRIMITIVES.get(key, (key, key))
    if 'anyOf' in schema or 'oneOf' in schema:
        choices = schema.get('anyOf', schema.get('oneOf'))
        nonnull = [x for x in choices if x.get('type') != 'null']
        if len(nonnull) == 1 and len(choices) == 2:
            rust, swift = type_pair(nonnull[0], name)
            return f'Nullable<{rust}>', f'HostNullable<{swift}>'
        sys.exit(f'Unsupported typed union: {name}')
    kind = schema.get('type')
    if kind is None and 'const' in schema:
        kind = 'boolean' if isinstance(schema['const'], bool) else 'string' if isinstance(schema['const'], str) else 'integer'
    if kind is None and 'enum' in schema and all(isinstance(v,str) for v in schema['enum']):
        kind = 'string'
    if isinstance(kind, list):
        other = [x for x in kind if x != 'null']
        if len(other) != 1 or 'null' not in kind:
            sys.exit(f'Unsupported type list: {name}')
        rust, swift = type_pair({**schema, 'type': other[0]}, name)
        return f'Nullable<{rust}>', f'HostNullable<{swift}>'
    if 'enum' in schema and kind == 'string':
        models.setdefault(name, schema)
        return name, name
    if kind == 'object':
        if schema.get('properties'):
            models.setdefault(name, schema)
            return name, name
        return 'serde_json::Value', 'HostJSONValue'
    if kind == 'array':
        rust, swift = type_pair(schema['items'], name + 'Item')
        return f'Vec<{rust}>', f'[{swift}]'
    if kind == 'integer':
        return ('u32', 'UInt32') if schema.get('maximum', 0) <= 4_294_967_295 else ('Serial', 'HostSerial')
    return {'string': ('String','String'), 'boolean': ('bool','Bool'), 'number': ('f64','Double')}[kind]

rust_files = {}
swift_files = {}
processed = set(PRIMITIVES)
while True:
    pending = [(name, schema) for name, schema in models.items() if name not in processed]
    if not pending:
        break
    for name, schema in pending:
        processed.add(name)
        rust = ['//! Generated native contract fields; validation/admission remain separate.\nuse super::*;\n']
        swift = ['// Generated by scripts/native_contracts.py.\nimport Foundation\n']
        if 'oneOf' in schema and all('$ref' in v for v in schema['oneOf']):
            variants=[v['$ref'].rsplit('/',1)[-1] for v in schema['oneOf']]
            rust.append(f'/// Typed native union `{name}`.\n#[derive(Clone, Debug, Serialize, Deserialize)]\n#[serde(untagged)]\npub enum {name} {{\n')
            swift.append(f'public enum {name}: Codable, Sendable {{\n')
            for variant in variants:
                rust.append(f'    /// Variant `{variant}`.\n    {variant}({variant}),\n')
                swift.append(f'  case {snake(variant)}({variant})\n')
            rust.append('}\n')
            swift.append('  public init(from decoder: Decoder) throws {\n    let c = try decoder.singleValueContainer()\n')
            for variant in variants:
                swift.append(f'    if let v = try? c.decode({variant}.self) {{ self = .{snake(variant)}(v); return }}\n')
            swift.append('    throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown native union variant"))\n  }\n  public func encode(to encoder: Encoder) throws {\n    switch self {\n')
            for variant in variants:
                swift.append(f'    case .{snake(variant)}(let v): try v.encode(to: encoder)\n')
            swift.append('    }\n  }\n}\n')
        elif schema.get('type') == 'string' and 'enum' in schema:
            rust.append('#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\n')
            rust.append(f'/// Contract enum `{name}`.\n')
            rust.append(f'pub enum {name} {{\n')
            swift.append(f'public enum {name}: String, Codable, Sendable {{\n')
            for value in schema['enum']:
                rust.append(f'    /// Contract value `{value}`.\n    #[serde(rename = {json.dumps(value)})]\n    {pascal(value)},\n')
                swift.append(f'  case `{snake(value)}` = {json.dumps(value)}\n')
            rust.append('}\n');swift.append('}\n')
        elif schema.get('type') == 'object':
            rust.append(f'/// Native contract `{name}`. Required nullable fields cannot be omitted.\n#[derive(Clone, Serialize, Deserialize)]\n#[serde(deny_unknown_fields)]\npub struct {name} {{\n')
            swift.append(f'public struct {name}: Codable, Sendable {{\n')
            required = schema.get('required', [])
            fields = []
            for key, prop in schema['properties'].items():
                rp, sp = type_pair(prop, name + pascal(key))
                optional = key not in required
                if optional:
                    rp, sp = f'Option<{rp}>', f'{sp}?'
                    rust.append('    #[serde(default, skip_serializing_if = "Option::is_none")]\n')
                rust.append(f'    /// Contract field `{key}`.\n    pub {key}: {rp},\n')
                swift.append(f'  public var {key}: {sp}\n')
                fields.append((key,sp,optional))
            rust.append('}\n')
            rust.append(f'impl std::fmt::Debug for {name} {{\n    fn fmt(&self, f: &mut std::fmt::Formatter<\'_>) -> std::fmt::Result {{ f.write_str("{name} {{ redacted }}") }}\n}}\n')
            swift.append('  private enum CodingKeys: String, CodingKey {\n' + ''.join(f'    case {key}\n' for key,_,_ in fields) + '  }\n')
            swift.append('  public init(from decoder: Decoder) throws {\n    let all = try decoder.container(keyedBy: HostCodingKey.self)\n')
            swift.append('    let allowed: Set<String> = [' + ','.join(json.dumps(k) for k,_,_ in fields) + ']\n')
            swift.append('    guard all.allKeys.allSatisfy({ allowed.contains($0.stringValue) }) else { throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: \"Unknown native contract field\")) }\n    let c = try decoder.container(keyedBy: CodingKeys.self)\n')
            for key,sp,optional in fields:
                swift.append(f'    self.{key} = try c.{"decodeIfPresent" if optional else "decode"}({sp.removesuffix("?")}.self, forKey: .{key})\n')
            swift.append('  }\n')
            swift.append('  public init(' + ', '.join(f'{k}: {t}' for k,t,_ in fields) + ') {\n' + ''.join(f'    self.{k} = {k}\n' for k,_,_ in fields) + '  }\n}\n')
        else:
            sys.exit(f'Unsupported top-level DTO: {name}')
        rust_files[f'crates/om-host-service/src/protocol/generated/{snake(name)}.rs'] = ''.join(rust)
        swift_files[f'macos/OpenMathNative/Generated/Contracts/{name}.swift'] = ''.join(swift)

mods = '// Generated by scripts/native_contracts.py.\nuse super::{Nullable, Serial};\nuse serde::{Serialize, Deserialize};\n'
for path in sorted(rust_files):
    module = Path(path).stem
    mods += f'mod {module};\npub use {module}::*;\n'
rust_files['crates/om-host-service/src/protocol/generated/mod.rs'] = mods
rust_files.update(swift_files)
rust_files['docs/design/native-contract-inputs.json'] = json.dumps({'schema_version': 1, 'inputs': inputs, 'generated_dto_count': len(processed - set(PRIMITIVES))},ensure_ascii=False,indent=2)+'\n'
# Canonical rustfmt output keeps generated contracts compatible with the workspace check.
staging = ROOT / 'target/native-contract-generation'
staging.mkdir(parents=True, exist_ok=True)
with tempfile.TemporaryDirectory(dir=staging) as tmp:
    paths = []
    for relative, text in rust_files.items():
        if not relative.endswith('.rs'):
            continue
        path = Path(tmp) / Path(relative).name
        path.write_text(text, encoding='utf-8')
        paths.append((relative, path))
    subprocess.run(['rustfmt', '--edition', '2024', '--config', 'skip_children=true'] + [str(p) for _,p in paths], check=True)
    for relative, path in paths:
        rust_files[relative] = path.read_text(encoding='utf-8')
abi = json.loads((ROOT / 'docs/design/native-host-abi.json').read_text(encoding='utf-8'))
header = '''/* Generated by scripts/native_contracts.py. Lifecycle implementations: R4.0.06. */
#ifndef OPENMATH_HOST_H
#define OPENMATH_HOST_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct om_host_handle om_host_handle;
typedef struct { unsigned char *ptr; size_t len; } om_host_buffer;
typedef struct { om_host_handle *handle; om_host_buffer error; } om_host_create_result;
/* Returned buffers are Rust-owned; free once (NULL/0 is empty). Version C string is static.
 * Handles are opaque registry keys: never dereference/free. close_finish is background-only.
 * cancel: 1 stop signalled, 0 terminal, -1 argument, -2 reference, -3 closing, -4 internal, -5 budget.
 * close_finish: 0 consumed, -2 invalid/consumed, -4 internal. No function unwinds across C. */
'''
for returned, name, args in abi['symbols']:
    header += f'{returned} {name}({args});\n'
header += '#ifdef __cplusplus\n}\n#endif\n#endif\n'
rust_files['macos/Headers/OpenMathHost.h'] = header
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for relative, text in rust_files.items():
    path = ROOT / relative
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8') != text:
            sys.exit(f'Native contract drift: {relative}')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8')
print(f'Native DTOs {"verified" if args.check else "generated"}: {len(processed)-len(PRIMITIVES)}')
